version: 0.2

phases:
  pre_build:
    commands:
      - git clone https://github.com/kunal3237/CodeForPractice.git
    
  build:
    
    commands:
      - docker built -t kunal3237/myfirtcodebuild .
      - echo "With Dockerfile"
    
  post_build:
    
    commands:
      - echo "Post_build also completed"

artifacts:
  files:
    - target/      
