version: 0.2

phases:
  pre_build:
    commands:
      - git clone https://github.com/kunal3237/CodeForPractice.git
      - docker login -u "kunal.sharma37@gmail.com" -p "Oscar3237$"
    
  build:
    
    commands:
      - docker build -t kunal3237/myfirstcodebuild .
      - docker push kunal3237/myfirstcodebuild kunal3237/myfirstcodebuild 
      - echo "With Dockerfile"
    
  post_build:
    
    commands:
      - echo "Post_build also completed"

artifacts:
  files:
    - '**/*'   
